image:
  repository: 852180292196.dkr.ecr.eu-west-1.amazonaws.com/cwep1airecrportalgene001/ms-spb-wh-representatives
  tag: 0.0.1

microservice: ms-spb-wh-representatives
namespace: generaltables
path: /customers/ms-spb-wh-representatives
hostname: portal.sceu.corp
secret_name: portal.sceu.corp
https: true
port: 8443
configurationFiles:
  - name: ms-spb-wh-representatives-config-map
    data: |-
      CLOUD_CONFIGURI: "http://ademma-config-server.globalsecurity"
      URL_COMMON: "https://portal.sceu.corp"
      URL_AS400: "https://asexp.scf.corp:40443"       
      NS_GLOBAL_SEC: "globalsecurity"
      SSL_KEYSTORE: file:/var/keystore/keystore.p12
      URL_JWK_SET_URI: "https://ademma-authorization-server.globalsecurity/ademma-authorization-server/oauth2/jwks"
      SERVER_PORT: "8443"
      CONFIG_URL_SPRINGDOC: "https://portal.sceu.corp/ms-spb-wh-representatives/v3/api-docs"
      SPRINGDOC_URL: "/v3/api-docs/swagger-config"
      HOST_PATH: "/customers/ms-spb-wh-representatives"
      APP_VERSION: "SNAPSHOT-0.0.1"
      LOGGING_LEVEL_ROOT: "INFO"
      LOGGING_LEVEL_APPLICATION: "INFO"
      DATADOG: "true"
Secrets:
  - cwepsslkeystorepass

secret_volume_name: cwepsslkeystore
secret_volume_path: "/var/keystore"